ToDoApplication/Models/ToDoItem.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ToDoApplication.Models
{
    public class ToDoItem
    {
        public long ToDoItemId { get; set; }

        [Required]
        public string Title { get; set; } = string.Empty;

        public string Description { get; set; } = string.Empty;

        public ToDoItemStatus Status { get; set; } = ToDoItemStatus.NotStarted;

        public DateTime CreationDate { get; set; } = DateTime.Now;

        [Required]
        public DateTime DueDate { get; set; } = DateTime.Now;

        public ICollection<ToDoItemNote>? ToDoItemNotes { get; set; }

        public long ToDoListId { get; set; }

        public ToDoList? ToDoList { get; set; }
    }
}

ToDoApplication/Controllers/ToDoItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ToDoApplication.Models;

namespace ToDoApplication.Controllers
{
    public class ToDoItemsController : Controller
    {
        private readonly ToDoListDbContext context;

        public ToDoItemsController(ToDoListDbContext context)
        {
            this.context = context;
        }

        // GET: ToDoItems
        public async Task<IActionResult> Index()
        {
            var toDoListDbContext = this.context.ToDoItems.Include(t => t.ToDoList).Where(t => t.DueDate.Date == DateTime.Today && t.ToDoList!.IsVisible && t.Status != ToDoItemStatus.Completed);
            return this.View(await toDoListDbContext.ToListAsync());
        }

        // GET: ToDoItems/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || this.context.ToDoItems == null)
            {
                return this.NotFound();
            }

            var toDoItem = await this.context.ToDoItems
                .Include(t => t.ToDoList)
                .FirstOrDefaultAsync(m => m.ToDoItemId == id);
            if (toDoItem == null)
            {
                return this.NotFound();
            }

            return this.View(toDoItem);
        }

        // GET: ToDoItems/Create

        public ViewResult Create(long listId)
        {
            ToDoItem toDoItem = new ToDoItem() { ToDoListId = listId };
            return this.View(toDoItem);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create2([Bind("ToDoItemId,Title,Description,Status,CreationDate,DueDate,ToDoListId")] ToDoItem toDoItem)
        {
            if (!this.ModelState.IsValid)
            {
                return this.BadRequest(this.ModelState);
            }
            else
            {
                this.context.Add(toDoItem);
                await this.context.SaveChangesAsync();
                return this.RedirectToAction("Tasks", "Home", new { id = toDoItem.ToDoListId });
            }
        }

        // GET: ToDoItems/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || this.context.ToDoItems == null)
            {
                return this.NotFound();
            }

            var toDoItem = await this.context.ToDoItems.FindAsync(id);
            if (toDoItem == null)
            {
                return this.NotFound();
            }

            this.ViewData["ToDoListId"] = new SelectList(this.context.ToDoLists, "ToDoListId", "ToDoListId", toDoItem.ToDoListId);
            return this.View(toDoItem);
        }

        // POST: ToDoItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("ToDoItemId,Title,Description,Status,CreationDate,DueDate,ToDoListId")] ToDoItem toDoItem)
        {
            if (id != toDoItem.ToDoItemId)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    this.context.Update(toDoItem);
                    await this.context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this.ToDoItemExists(toDoItem.ToDoItemId))
                    {
                        return this.NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return this.RedirectToAction("Tasks", "Home", new { id = toDoItem.ToDoListId });
            }

            this.ViewData["ToDoListId"] = new SelectList(this.context.ToDoLists, "ToDoListId", "ToDoListId", toDoItem.ToDoListId);
            return this.View(toDoItem);
        }

        // GET: ToDoItems/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || this.context.ToDoItems == null)
            {
                return this.NotFound();
            }

            var toDoItem = await this.context.ToDoItems
                .Include(t => t.ToDoList)
                .FirstOrDefaultAsync(m => m.ToDoItemId == id);
            if (toDoItem == null)
            {
                return this.NotFound();
            }

            return this.View(toDoItem);
        }

        // POST: ToDoItems/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (this.context.ToDoItems == null)
            {
                return this.Problem("Entity set 'ToDoListDbContext.ToDoItems'  is null.");
            }

            var toDoItem = await this.context.ToDoItems.FindAsync(id);
            if (toDoItem != null)
            {
                this.context.ToDoItems.Remove(toDoItem);
            }
            
            await this.context.SaveChangesAsync();
            return this.RedirectToAction("Tasks", "Home", new { id = toDoItem!.ToDoListId });
        }

        private bool ToDoItemExists(long id)
        {
          return this.context.ToDoItems.Any(e => e.ToDoItemId == id);
        }
    }
}

ToDoApplication/Views/ToDoItems/Create.cshtml
@model ToDoApplication.Models.ToDoItem

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ToDoItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Create2", "ToDoItems", FormMethod.Post))
        {
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control" asp-items="Html.GetEnumSelectList<ToDoItemStatus>()"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <input type="hidden" name="ToDoListId" value=@Model?.ToDoListId>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ToDoApplication/Views/ToDoItems/Delete.cshtml
@model ToDoApplication.Models.ToDoItem

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ToDoItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ToDoList)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ToDoList.ToDoListId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ToDoItemId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ToDoApplication/Views/ToDoItems/Details.cshtml
@model ToDoApplication.Models.ToDoItem

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ToDoItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ToDoList)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ToDoList!.ToDoListTitle)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

ToDoApplication/Views/ToDoItems/Edit.cshtml
@model ToDoApplication.Models.ToDoItem

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ToDoItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ToDoItemId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control" asp-items="Html.GetEnumSelectList<ToDoItemStatus>()"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <input type="hidden" name="ToDoListId" value=@Model?.ToDoItemId>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ToDoApplication/Views/ToDoItems/Index.cshtml
@model IEnumerable<ToDoApplication.Models.ToDoItem>

@{
    ViewData["Title"] = "Index";
}

<h1>Tasks Due Today</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DueDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ToDoList)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DueDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ToDoList!.ToDoListTitle)
            </td>

                <td>
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle bi bi-three-dots-vertical" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <span class="bi bi-three-dots-vertical"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>
                                <a asp-controller="ToDoItemNotes" asp-action="TaskNotes" asp-route-id="@item.ToDoItemId">Notes</a>
                            </li>
                            <li>
                                <a asp-action="Edit" asp-route-id="@item.ToDoItemId">Edit</a>
                            </li>
                            <li>
                                <a asp-action="Details" asp-route-id="@item.ToDoItemId">Details</a>
                            </li>
                             <li>
                                <a asp-action="Delete" asp-route-id="@item.ToDoItemId">Delete</a>
                            </li>
                        </ul>
                    </div>
                </td>
        </tr>
}
    </tbody>
</table>