ToDoApplication/Controllers/ToDoListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ToDoApplication.Models;

namespace ToDoApplication.Controllers
{
    public class ToDoListsController : Controller
    {
        private readonly ToDoListDbContext context;

        public ToDoListsController(ToDoListDbContext context)
        {
            this.context = context;
        }

        // GET: ToDoLists/Create
        public IActionResult Create()
        {
            return this.View();
        }

        // POST: ToDoLists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ToDoListId,ToDoListTitle,IsVisible")] ToDoList toDoList)
        {
            if (!this.ModelState.IsValid)
            {
                return this.BadRequest(this.ModelState);
            }
            else
            {
                this.context.Add(toDoList);
                await this.context.SaveChangesAsync();
                return this.RedirectToAction("Index", "Home");
            }
        }

        // GET: ToDoLists/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || this.context.ToDoLists == null)
            {
                return this.NotFound();
            }

            var toDoList = await this.context.ToDoLists.FindAsync(id);
            if (toDoList == null)
            {
                return this.NotFound();
            }

            return this.View(toDoList);
        }

        // POST: ToDoLists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("ToDoListId,ToDoListTitle,IsVisible")] ToDoList toDoList)
        {
            if (id != toDoList.ToDoListId)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    this.context.Update(toDoList);
                    await this.context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this.ToDoListExists(toDoList.ToDoListId))
                    {
                        return this.NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return this.RedirectToAction("Index", "Home");
            }

            return this.View(toDoList);
        }

        // GET: ToDoLists/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || this.context.ToDoLists == null)
            {
                return this.NotFound();
            }

            var toDoList = await this.context.ToDoLists
                .FirstOrDefaultAsync(m => m.ToDoListId == id);
            if (toDoList == null)
            {
                return this.NotFound();
            }

            return this.View(toDoList);
        }

        // POST: ToDoLists/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (this.context.ToDoLists == null)
            {
                return this.Problem("Entity set 'ToDoListDbContext.ToDoLists'  is null.");
            }

            var toDoList = await this.context.ToDoLists.FindAsync(id);
            if (toDoList != null)
            {
                this.context.ToDoLists.Remove(toDoList);
            }
            
            await this.context.SaveChangesAsync();
            return this.RedirectToAction("Index", "Home");
        }

        private bool ToDoListExists(long id)
        {
          return this.context.ToDoLists.Any(e => e.ToDoListId == id);
        }
    }
}

ToDoApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ToDoListApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/all.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/ToDoApplication.styles.css" asp-append-version="true" />
</head>
<body>

    <div class="bg-primary text-white p-2">
        <span class="navbar-brand ml-2">
            <a asp-Controller="Home" asp-action="Index"> <i class="fa-solid fa-house " style="color:white"></i></a>

            ToDo Application
        </span>

    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="align-self-center">
            @RenderBody()

        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDoApplication/Views/Shared/_ToDoListSummary.cshtml
@using ToDoApplication.ExtensionMethods
@model ToDoList

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model?.ToDoListTitle
               <a asp-action="Tasks" asp-route-id="@Model?.ToDoListId">Tasks</a> |
               <a asp-controller="ToDoLists" asp-action="Edit" asp-route-id="@Model?.ToDoListId">Edit List</a> |
               <a asp-controller="ToDoLists" asp-action="Delete" asp-route-id="@Model?.ToDoListId">Delete List</a> |
            <span class="badge rounded-pill bg-primary text-white"
                  style="float:right">
                <small>@Model?.IsVisible.StringToListVisibillity()</small>
            </span>
        </h4>
    </div>
</div>