ToDoApplication/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Migrations;
using ToDoApplication.Models.Repositories;

namespace ToDoApplication.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
       public IViewComponentResult Invoke()
       {
            List<string> toDoListStatuses = new List<string> { "Active", "Hidden", "All" };

            this.ViewBag.SelectedToDoListStatus = this.RouteData?.Values["toDoListStatus"];

            return this.View(toDoListStatuses);
       }
    }
}

ToDoApplication/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;
using ToDoApplication.ExtensionMethods;
using ToDoApplication.Models;
using ToDoApplication.Models.Repositories;
using ToDoApplication.Models.ViewModels;

namespace ToDoApplication.Controllers
{
    public class HomeController : Controller
    { 
        private readonly IToDoListRepository repository;

        public HomeController(IToDoListRepository repository)
        {
            this.repository = repository;
        }

        public int PageSize { get; set; } = 4;

        public ViewResult Index(string toDoListStatus = "Active", int toDoListPage = 1)
        {
            IEnumerable<ToDoList> toDoLists;
            toDoLists = this.repository.ToDoLists;

            if(toDoListStatus.StringToListVisibillity() == ToDoListVisibility.Active)
            {
                toDoLists = toDoLists.Where(toDoList => toDoList.IsVisible);
            }

            if (toDoListStatus.StringToListVisibillity() == ToDoListVisibility.Hidden)
            {
                toDoLists = toDoLists.Where(toDoList => !toDoList.IsVisible);
            }

            int toDoListsPageCount = toDoLists.Count();

            return this.View(new ToDoListListViewModel
            {
                ToDoLists = toDoLists
                              .OrderBy(p => p.ToDoListId)
                              .Skip((toDoListPage - 1) * this.PageSize)
                              .Take(this.PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = toDoListPage,
                    ItemsPerPage = this.PageSize,
                    TotalItems = toDoListStatus == null ? this.repository.ToDoLists.Count() : toDoListsPageCount,
                },
                CurrentToDoListStatus = toDoListStatus!,
            });
        }

        public async Task<IActionResult> Tasks(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var toDoList = await this.repository.ToDoLists
                .Include(s => s.ToDoItems)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ToDoListId == id);

            if (toDoList == null)
            {
                return this.NotFound();
            }

            return this.View(toDoList);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

ToDoApplication/Views/Home/Index.cshtml
@model ToDoListListViewModel

@{
    ViewData["Title"] = "Home Page";
}

@{
    var route = this.Model.CurrentToDoListStatus is null ? "pagination" :"toDoListStatusPage";
}
    <div class="row m-1 p-1">
        <div id="categories" class="align-self-center">
            <vc:navigation-menu />
        </div>
    </div>
@foreach (var p in Model?.ToDoLists ?? Enumerable.Empty<ToDoList>())
{
    <partial name = "_ToDoListSummary" model = "p" />
}

<div page-model="@Model?.PagingInfo" page-classes-enabled="true" page-route=@route
     page-class="btn" page-class-normal="btn-outline-dark"
     page-class-selected="btn-primary" page-url-toDoListStatus="@Model?.CurrentToDoListStatus!"
     class="btn-group pull-right m-1">
</div>

ToDoApplication/Views/Home/Tasks.cshtml
@model ToDoApplication.Models.ToDoList

@{
    ViewData["Title"] = "Details";
}

<h1>Tasks</h1>

<div>
    <h4>Tasks</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ToDoListTitle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ToDoListTitle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsVisible)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsVisible)
        </dd>
        <dd class="col-sm-10">
            <a asp-route="CreateToDoItem" asp-route-listId="@Model?.ToDoListId"><i class="fa-solid fa-plus-circle fa-lg" style="color:black"></i></a>
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ToDoItems)
        </dt>


        <dd class="col-sm-10">
            <table class="table">
                <tr>
                    <th>Task</th>
                    <th>Status</th>
                    <th>DueDate</th>
                </tr>
                @foreach (var task in Model?.ToDoItems ?? Enumerable.Empty<ToDoApplication.Models.ToDoItem>())
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => task.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => task.Status)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => task.DueDate)
                        </td>
                        <td> 
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                   <span class="bi bi-three-dots-vertical"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item" asp-controller="ToDoItemNotes" asp-action="TaskNotes" asp-route-id="@task.ToDoItemId">Notes</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-Controller="ToDoItems" asp-action="Edit" asp-route-id="@task.ToDoItemId">Edit</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-Controller="ToDoItems" asp-action="Details" asp-route-id="@task.ToDoItemId">Details</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-Controller="ToDoItems" asp-action="Delete" asp-route-id="@task.ToDoItemId">Delete</a>
                                    </li>
                                </ul>
                            </div>                
                        </td>
                    </tr>
                }
            </table>
        </dd>
    </dl>
</div>
<div>
</div>